### ISSUE TITLE
MemberExtendedMergeVarSerializer Doesn't Implement the setDispatcher Function

### ISSUE THREAD

**Issue by dagostinelli** [orocrm/OroCRMMailChimpBundle#9]
I've installed the bundle and then attempted to click on the Import button in the OroCRM GUI to import some records.  When I do so, I am met with this:

`PHP Fatal error:  Call to undefined method OroCRM\\Bundle\\MailChimpBundle\\ImportExport\\Serializer\\MemberExtendedMergeVarSerializer::setDispatcher() in /var/www/orocrm/app/cache/prod/appProdProjectContainer.php on line 13, referer: http://mysite.blah.com/app.php/account
`
I grep'd for setDispatcher and it only came up in `services.yml`.  Did someone forget to implement this?

In 
`/vendor/oro/crm-mail-chimp/src/OroCRM/Bundle/MailChimpBundle/Resources/config/services.yml`

I see this:

```
orocrm_mailchimp.importexport.serializer.memeber_extended_merge_var:
        class: %orocrm_mailchimp.importexport.serializer.memeber_extended_merge_var.class%
        arguments:
            - @oro_importexport.field.field_helper
            - @oro_importexport.field.database_helper
            - @orocrm_mailchimp.marketinglist.datagrid_provider
            - @translator
            - @oro_locale.formatter.number
            - @oro_locale.formatter.date_time
            - %orocrm_mailchimp.entity.member_extended_merge_var.class%
        calls:
            - [setDispatcher, [@event_dispatcher]]
        tags:
            - { name: oro_importexport.normalizer }
```

Which mentions `setDispatcher()`

When I grep for `setDispatcher` in the entire code base of OroCRMMailChimpBundle, it is not there.  

How do I fix this error?
